---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: zenix
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
      - https://download.docker.com/linux/fedora/docker-ce.repo
      - https://copr.fedorainfracloud.org/coprs/abn/throttled/repo/fedora-42/abn-throttled-fedora-42.repo
      - https://copr.fedorainfracloud.org/coprs/sneexy/python-validity/repo/fedora-42/sneexy-python-validity-fedora-42.repo
    install:
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-42.noarch.rpm
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-42.noarch.rpm
      - vim
      - neovim
      - bat
      - eza
      - starship
      - fzf
      - ripgrep
      - jq
      - fd-find
      - fish
      - terra-release
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - steam-devices
      - throttled
      - open-fprintd
      - fprintd-clients
      - fprintd-clients-pam
      - python3-validity
      - baobab
      - cryfs
      - adw-gtk3-theme
      - gnome-shell-extension-pop-shell
      - xprop
      - dotnet-sdk-8.0
      - dotnet-sdk-9.0
      - dotnet-sdk-8.0-source-built-artifacts
      - dotnet-sdk-9.0-source-built-artifacts
      - aspnetcore-runtime-8.0
      - aspnetcore-runtime-9.0
      - java-21-openjdk
      - java-latest-openjdk
      - rust
      - rust-analyzer
      - cargo
      - golang
      - gopls
      - nodejs
      - nodejs-npm
      - llvm
      - clang
      - cmake
      - meson
      - ninja-build
      - pandoc
      - texlive-scheme-basic
      - typst
      - nerd-fonts
    remove:
      - firefox
      - firefox-langpacks
      - fprintd 
      - fprintd-pam
      - thermald
      - gnome-system-monitor

  - type: dnf
    # install the Fedora Virtualization group
    group-install:
      with-optional: false
      packages:
        - virtualization
        - c-development
        - development-tools

  - type: default-flatpaks
    configurations:
      - scope: system
        repo:
          title: Flathub (system)
        install:
          - org.gnome.Papers
          - org.gnome.Loupe
          - org.gnome.SimpleScan
          - org.gnome.Characters
          - org.gnome.Decibels
          - org.gnome.Logs
          - org.gnome.Contacts
          - org.gnome.font-viewer
          - org.gnome.Maps
          - org.gnome.clocks
          - org.gnome.Weather
          - org.gnome.TextEditor
          - org.gnome.Calendar
          - com.mattjakeman.ExtensionManager
          - io.gitlab.adhami3310.Impression
          - org.gnome.seahorse.Application
          - org.gnome.Connections
          - org.gnome.Snapshot
          - org.gnome.Calculator
          - page.tesk.Refine
          - io.github.realmazharhussain.GdmSettings
          - org.mozilla.firefox
          - io.missioncenter.MissionCenter
          - com.github.tchx84.Flatseal
          - page.codeberg.libre_menu_editor.LibreMenuEditor
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
