---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: zenix
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-42.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-42.noarch.rpm
      - https://download.docker.com/linux/fedora/docker-ce.repo
      - https://copr.fedorainfracloud.org/coprs/abn/throttled/repo/fedora-42/abn-throttled-fedora-42.repo
      - https://copr.fedorainfracloud.org/coprs/sneexy/python-validity/repo/fedora-42/sneexy-python-validity-fedora-42.repo
    install:
      - vim
      - neovim
      - bat
      - eza
      - starship
      - fzf
      - ripgrep
      - jq
      - fd-find
      - fish
      - terra-release
      - kate
      - krename
      - yakuake
      - okular
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - steam-devices
      - throttled
      - open-fprintd
      - fprintd-clients
      - fprintd-clients-pam
      - python3-validity
    remove:
      - firefox
      - firefox-langpacks
      - fprintd 
      - fprintd-pam
      - thermald

  - type: dnf
    # install the Fedora Virtualization group
    group-install:
      with-optional: false
      packages:
        - virtualization

  - type: default-flatpaks
    configurations:
      notify: false # Send notification after install/uninstall is finished
      scope: system
      repo:
        - url: https://dl.flathub.org/repo/flathub.flatpakrepo
        - name: flathub
        - title: Flathub
      install:
        - org.kde.elisa
        - org.videolan.VLC
        - ch.protonmail.protonmail-bridge
        - com.bitwarden.desktop
        - com.github.jeromerobert.pdfarranger
        - com.github.xournalpp.xournalpp
        - com.jgraph.drawio.desktop
        - com.nextcloud.desktopclient.nextcloud
        - com.obsproject.Studio
        - com.protonvpn.www
        - fr.handbrake.ghb
        - io.dbeaver.DBeaverCommunity
        - io.github.Qalculate
        - md.obsidian.Obsidian
        - org.geogebra.GeoGebra
        - org.gimp.GIMP
        - org.inkscape.Inkscape
        - org.kde.kdenlive
        - org.kde.krita
        - org.mozilla.Thunderbird
        - org.mozilla.firefox
        - org.onlyoffice.desktopeditors
        - org.qbittorrent.qBittorrent
        - org.signal.Signal
        - com.rtosta.zapzap
        - org.tenacityaudio.Tenacity
        - rest.insomnia.Insomnia
        - org.freac.freac
        - org.rncbc.qpwgraph
        - com.github.Flacon
        - org.kde.kdiff3
        - org.kde.isoimagewriter

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

